#pragma once

#include <nsmb_nitro.hpp>
#include <type_traits>
#include <optional>

#include "glue/hash.hpp"

// Every type a module names in its level-data has to be complete by the time
// the generated getters below are included, and the generator only knows type
// names, not the headers they live in. glue declares one such key of its own.
#include "glue/stageobject.hpp"

namespace Glue::Level {

// These templates must be force inlined with NTR_INLINE
// to avoid generating extra out-of-line template instantiations and function calls.
//
// Example: With force inline (NTR_INLINE), the compiler directly emits the logic for each use site,
// resulting in smaller and faster code, especially for small accessor templates.
//
// Example assembly with force inline:
//   - No calls to getValue<T>; logic is inlined into the caller.
//   - Only calls to findData remain.
//   - No stack usage for std::optional temporaries.
//
// Example assembly without force inline:
//   - getValue<T> is emitted as a separate function.
//   - Each use site calls getValue<T>, passing arguments on the stack.
//   - Extra stack usage and code size from std::optional temporaries and function call overhead.
//
// For embedded/console targets, forced inlining is critical for performance and code size.

// Flags are stored separately from data entries, allowing us to use 1+N u32s (1 for count, N for hash) instead of 2N u32s (hash and empty offset together).

// The accessors below reinterpret bytes out of the level block, so what they
// require of T is that copying it that way is meaningful -- not that it is a
// number. `level-data:` can name any type, and a struct is as valid an entry
// as a u32.

template<class T>
struct SizedArray {
	u32 size = 0;
	T* values = nullptr;
};

struct GlueBlock {

	struct FlagInfo {
		u32 hash;
	};

	struct DataEntry {
		u32 hash;
		u32 offset;
	};

	u32 flagCount;
	// FlagsInfo flagInfos[];
	// DataEntry valueInfos[];
	// u8 data[];

	DataEntry* getDataEntries();
	bool hasFlag(u32 hash);
	GlueBlock::DataEntry* findDataEntry(u32 hash);

};

bool hasGlueBlock();
GlueBlock* getGlueBlock();
bool hasFlag(Hash hash);
void* findData(Hash hash);

template<class T>
NTR_INLINE std::optional<T> getValue(Hash hash) {
	static_assert(std::is_trivially_copyable_v<T>, "getValue<T> only supports trivially copyable types");

	void* data = findData(hash);
	if (data == nullptr) {
		return {};
	}

	return { *rcast<T*>(data) };
}

template<class T>
NTR_INLINE std::optional<T*> getArray(Hash hash) {
	static_assert(std::is_trivially_copyable_v<T>, "getArray<T> only supports trivially copyable types");

	void* data = findData(hash);
	if (data == nullptr) {
		return {};
	}

	return { rcast<T*>(data) };
}

template<class T>
NTR_INLINE std::optional<SizedArray<T>> getSizedArray(Hash hash) {
	static_assert(std::is_trivially_copyable_v<T>, "getSizedArray<T> only supports trivially copyable types");

	u32* data = rcast<u32*>(findData(hash));
	if (data == nullptr) {
		return {};
	}

	// Named, because std::optional has no two-argument converting constructor
	// to aggregate-initialize the SizedArray through.
	return SizedArray<T>{ *data, rcast<T*>(data + 1) };
}

template<class T>
NTR_INLINE T getValueOr(Hash hash, T defaultValue = {}) {
	static_assert(std::is_trivially_copyable_v<T>, "getValueOr<T> only supports trivially copyable types");
	return getValue<T>(hash).value_or(defaultValue);
}

template<class T>
NTR_INLINE T* getArrayOr(Hash hash, T* defaultValue = nullptr) {
	static_assert(std::is_trivially_copyable_v<T>, "getArrayOr<T> only supports trivially copyable types");
	return getArray<T>(hash).value_or(defaultValue);
}

template<class T>
NTR_INLINE SizedArray<T> getSizedArrayOr(Hash hash, SizedArray<T> defaultValue = {}) {
	static_assert(std::is_trivially_copyable_v<T>, "getSizedArrayOr<T> only supports trivially copyable types");
	return getSizedArray<T>(hash).value_or(defaultValue);
}

template<std::size_t N>
class CTString {
public:
	static constexpr std::size_t Size = N;

	consteval CTString(const char (&string)[N]) {
		for (std::size_t i = 0; i < N; i++) {
			data[i] = string[i];
		}
	}

	char data[N];
};

// Type traits for each key (autogenerated by nsmbtool)
template<CTString HashStr>
struct GetterGetDataType; // Primary template left undefined

// Type alias for cleaner code
template<CTString HashStr>
using GetterDataType = typename GetterGetDataType<HashStr>::type;

// Include auto-generated header
#include "generated/glue/level_data_getters.hpp"

template<CTString HashStr>
NTR_INLINE GetterDataType<HashStr> getOr(GetterDataType<HashStr> defaultValue = {}) {
	return get<HashStr>().value_or(defaultValue);
}

} // namespace Glue::Level
