#!/usr/bin/env python3
"""Generate NSMB Co-op assets from NCPatcher's resolved module graph."""

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path

from project_config import get_script_project_config


@dataclass
class ObjectRegistration:
    name: str
    obj_type: str
    module_id: str
    component_name: str
    header_path: str
    overlay: int | None
    obj_id: int = 0


class ModuleAssetGenerator:
    def __init__(self, graph: dict, output_dir: Path, map_filename: str):
        if graph.get('schema') != 'ncpatcher.modules/1':
            raise ValueError('unsupported or missing NCPatcher module graph schema')

        self.graph = graph
        self.output_dir = output_dir
        self.map_filename = map_filename
        self.project_root = Path(graph['dir']).parent
        self.languages = set(get_script_project_config().language_codes)
        self.registrations: list[ObjectRegistration] = []

    @staticmethod
    def _as_list(value):
        if value is None:
            return []
        return value if isinstance(value, list) else [value]

    def _enabled_modules(self):
        return (module for module in self.graph.get('modules', []) if module.get('enabled'))

    def _is_excluded(self, relative: Path, excluded: set[str]) -> bool:
        text = relative.as_posix()
        without_language = '/'.join(relative.parts[1:]) if relative.parts and relative.parts[0] in self.languages else text
        return any(text == pattern or without_language == pattern or text.endswith('/' + pattern)
                   for pattern in excluded)

    def generate_nitrofs_map(self):
        file_map: dict[str, str] = {}

        for module in self._enabled_modules():
            module_dir = Path(module['dir'])
            nitrofs_dir = module_dir / 'nitrofs'
            if not nitrofs_dir.is_dir():
                continue

            excluded = {
                str(pattern)
                for component in module.get('components', [])
                if not component.get('enabled', True)
                for pattern in self._as_list(component.get('files'))
            }

            for source in sorted(path for path in nitrofs_dir.rglob('*') if path.is_file()):
                destination = source.relative_to(nitrofs_dir)
                if self._is_excluded(destination, excluded):
                    continue

                try:
                    source_text = source.relative_to(self.project_root).as_posix()
                except ValueError:
                    source_text = source.as_posix()
                file_map.setdefault(destination.as_posix(), source_text)

        self.output_dir.mkdir(parents=True, exist_ok=True)
        output = self.output_dir / self.map_filename
        with output.open('w', encoding='utf-8') as stream:
            stream.write('# Nitrofs file mapping generated by module_gen.py\n')
            stream.write('# Format: relative_path=absolute_source_path\n')
            stream.write(f'# Generated from {len(file_map)} files\n\n')
            for destination, source in sorted(file_map.items()):
                stream.write(f'{destination}={source}\n')

        print(f'Generated NitroFS map with {len(file_map)} files: {output}')

    def collect_objects(self):
        registrations = []

        for module in self._enabled_modules():
            module_id = module.get('id')
            if not module_id:
                raise ValueError(f"enabled module {module.get('key', '<unknown>')} has no id")

            for component in module.get('components', []):
                if not component.get('enabled', True):
                    continue

                target = component.get('target') or {}
                overlay = target.get('overlay')
                for obj in self._as_list(component.get('extra', {}).get('objects')):
                    if not isinstance(obj, dict) or not obj.get('name') or not obj.get('header'):
                        raise ValueError(f"invalid object in {module_id}.{component.get('name', '<unknown>')}")
                    obj_type = obj.get('type', 'actor')
                    if obj_type not in ('actor', 'scene'):
                        raise ValueError(f"object {obj['name']} has invalid type {obj_type}")

                    registrations.append(ObjectRegistration(
                        name=obj['name'],
                        obj_type=obj_type,
                        module_id=module_id,
                        component_name=component['name'],
                        header_path=obj['header'],
                        overlay=overlay,
                    ))

        registrations.sort(key=lambda item: (item.module_id, item.component_name, item.name))
        seen = set()
        for index, registration in enumerate(registrations, start=0x182):
            identity = (registration.module_id, registration.name)
            if identity in seen:
                raise ValueError(f'duplicate object {registration.module_id}.{registration.name}')
            seen.add(identity)
            registration.obj_id = index

        self.registrations = registrations
        print(f'Collected {len(registrations)} object registrations')

    def generate_object_headers(self):
        include_dir = self.output_dir / 'include'
        object_dir = include_dir / 'objectids'
        object_dir.mkdir(parents=True, exist_ok=True)

        by_module: dict[str, list[ObjectRegistration]] = {}
        for registration in self.registrations:
            by_module.setdefault(registration.module_id, []).append(registration)

        for module_id, registrations in by_module.items():
            lines = [
                '#pragma once', '', '#include <cstdint>', '',
                f'// Generated object IDs for module ID: {module_id}',
                '// Do not edit this file directly', '',
                f'namespace ObjectID::{module_id} {{', '',
            ]
            lines.extend(f'    static constexpr std::uint16_t {item.name} = 0x{item.obj_id:X};'
                         for item in registrations)
            lines.extend(['', '}', ''])
            (object_dir / f'{module_id.lower()}.hpp').write_text('\n'.join(lines), encoding='utf-8')

        registry = [
            '#pragma once', '', '#include <cstdint>', '',
            '// Generated object registry', '// Do not edit this file directly', '',
        ]
        registry.extend(f'#include "objectids/{module_id.lower()}.hpp"' for module_id in by_module)
        registry.extend([
            '', 'namespace Game {',
            '    static constexpr std::uint16_t ExtendedObjectsStart = 0x182;',
            f'    static constexpr std::uint16_t ExtendedObjectsCount = {len(self.registrations)};',
            '}', '',
        ])
        (include_dir / 'object_registry.hpp').write_text('\n'.join(registry), encoding='utf-8')

        profile = [
            '#pragma once', '',
            '// Generated profile table for extended objects',
            '// Do not edit this file directly', '',
        ]
        headers = dict.fromkeys(item.header_path for item in self.registrations)
        profile.extend(f'#include "{header}"' for header in headers)
        profile.extend([
            '', 'namespace Game {', '', '// Generated extended profile table',
            'const ObjectProfile* mainExtPT[] = {',
        ])
        profile.extend(f'    &{item.name}::Profile,  // {item.name} (0x{item.obj_id:X})'
                       for item in self.registrations)
        profile.extend([
            '};', '', 'constinit const ObjectProfile* const* currentExtPT = mainExtPT;', '', '}', '',
        ])
        (include_dir / 'extended_profiles.hpp').write_text('\n'.join(profile), encoding='utf-8')

        print(f'Generated object headers: {include_dir}')

    def generate_scene_registry(self):
        scenes = [item for item in self.registrations
                  if item.obj_type == 'scene' and item.overlay is not None]
        module_ids = sorted({item.module_id for item in scenes})
        lines = [
            '#pragma once', '', '#include <nsmb_nitro.hpp>', '',
            '// Generated scene overlay registry',
            '// Do not edit this file directly', '',
        ]
        lines.extend(f'#include "objectids/{module_id.lower()}.hpp"' for module_id in module_ids)
        if module_ids:
            lines.append('')

        if scenes:
            lines.extend([
                'NTR_INLINE u32 getSceneOverlayID(u16 sceneID, u32 defaultOverlayID) {', '',
                '    switch (sceneID) {',
            ])
            lines.extend(
                f'        case ObjectID::{item.module_id}::{item.name}: return {item.overlay};'
                for item in sorted(scenes, key=lambda item: (item.module_id, item.name))
            )
            lines.extend([
                '        default: return defaultOverlayID;', '    }', '', '}',
            ])
        else:
            lines.append('#define PROCESS_NO_SCENE_IN_OVERLAY')
        lines.append('')

        output = self.output_dir / 'include' / 'scene_overlay_registry.hpp'
        output.write_text('\n'.join(lines), encoding='utf-8')
        print(f'Generated scene overlay registry: {output}')

    def run(self):
        self.generate_nitrofs_map()
        self.collect_objects()
        self.generate_object_headers()
        self.generate_scene_registry()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--graph', type=Path, required=True,
                        help='NCPatcher ncpatcher.modules/1 graph JSON')
    parser.add_argument('--out-dir', type=Path, default=Path('build/generated'))
    parser.add_argument('--nitrofs-map-file', default='nitrofs_file_map.txt')
    args = parser.parse_args()

    try:
        with args.graph.open(encoding='utf-8') as stream:
            graph = json.load(stream)
        ModuleAssetGenerator(graph, args.out_dir, args.nitrofs_map_file).run()
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f'error: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
